service: tome

frameworkVersion: '3'

plugins:
  - serverless-iam-roles-per-function
  - serverless-python-requirements

provider:
  name: aws
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  stackName: tome-${opt:stage, 'dev'}
  deploymentMethod: direct
  runtime: python3.11
  config: ${file(../config/${opt:stage, 'dev'}.yml)}	
  httpApi:
    cors: true


custom:
  env: ${self:provider.config.env}
  prefix: tome-${self:custom.env}
  userTable: ${self:custom.prefix}-userTable
  serverConfigTable: ${self:custom.prefix}-serverConfigTable
  pythonRequirements:
    useStaticCache: false
    useDownloadCache: false
    noDeploy: []
    slim: true
    layer:
      compatibleRuntimes:
        - python3.11

package:
  individually: true
  patterns:
    - '!./**'
  
functions:
  loginService:
    name: ${self:custom.prefix}-loginService
    description: tome endpoint for log in and authentication
    handler: lambdas/loginService.handler
    events:
    - httpApi:
        path: /health
        method: GET
    - httpApi:
        path: /register
        method: POST
    - httpApi:
        path: /login
        method: POST
    - httpApi:
        path: /verify
        method: POST 
    layers: 
      - !Ref PythonRequirementsLambdaLayer
    package:
      patterns:
        - lambdas/loginService.py
        - lambdas/utils.py
    timeout: 6
    memorySize: 128
    environment:
      LOG_LEVEL: logging.INFO
      USER_TABLE: ${self:custom.userTable}
      SECRET_KEY: ${self:provider.config.secret}
    iamRoleStatementsName: ${self:custom.prefix}-login-role
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:*
        Resource: 
          - arn:aws:dynamodb:${self:provider.config.region}:${self:provider.config.account}:table/${self:custom.userTable}
          - arn:aws:dynamodb:${self:provider.config.region}:${self:provider.config.account}:table/${self:custom.userTable}/*


resources:

  Resources:

    # table of user info used for auth
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.userTable}
        AttributeDefinitions:
          - AttributeName: username
            AttributeType: S
        KeySchema:
          - AttributeName: username
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    # table of server/game settings
    # serverConfigTable:
    #   Type: AWS::DynamoDB::Table
    #   Properties:
    #     TableName: ${self:custom.serverConfigTable}
    #     AttributeDefinitions:
    #       - AttributeName: guildId
    #         AttributeType: S
    #     KeySchema:
    #       - AttributeName: guildId
    #         KeyType: HASH
    #     BillingMode: PAY_PER_REQUEST


  Outputs:
    UsersTable: 
      Value: ${self:custom.userTable}